lockfile: "/tmp/goodnight_mouse.pid"
rules:
  - name: default
    match:
      - application: '.*'
    # keys: "fjdkghsla"
    keys: "abc"
    colors:
      border: "#FF0000"
      background: "rgba(0, 100%, 0, 0.2)"
      text: "#0000FF"
      active_text: "#FFFF00"
    states:
      - STATE_SHOWING
      - STATE_VISIBLE
      - STATE_ENABLED
      - STATE_SENSITIVE
    roles:
      ROLE_PUSH_BUTTON: actuate
      ROLE_TOGGLE_BUTTON: actuate
      ROLE_COMBO_BOX: actuate
      ROLE_MENU: actuate
      ROLE_MENU_ITEM: actuate
      ROLE_PAGE_TAB: actuate_non_selected
      ROLE_RADIO_BUTTON: actuate
      ROLE_SPIN_BUTTON: actuate
      ROLE_CHECK_BOX: actuate
      ROLE_CHECK_MENU_ITEM: actuate
      ROLE_LINK: actuate
      ROLE_TEXT: focus
      ROLE_ENTRY: focus
      ROLE_PASSWORD_TEXT: focus
      ROLE_SLIDER: focus
      ROLE_DIAL: actuate
      ROLE_DATE_EDITOR: focus
functions:
  actuate:
    match:
      - action: '.*'
    return: native
    else:
      match:
        - states:
          - STATE_FOCUSABLE
      return: press
      else:
        return: click
  actuate_non_selected:
    match:
      - states:
          - STATE_SELECTED
        invert: true
    goto: actuate
  focus:
    match:
      - states:
          - STATE_FOCUSABLE
      - states:
          - STATE_FOCUSED
        invert: true
    return: focus