lockfile: "/tmp/goodnight_mouse.pid"
rules:
  - name: default
    match:
      - application: '.*'
    # keys: "fjdkghsla"
    keys: "abc"
    css: |
      /*.action_window {
        border-color: #FF0000;
        border-style: solid;
        border-width: 2pt;
        background-color: rgba(0, 100%, 0, 0.5);
        border-radius: 2pt;
      }
      .action_character {
        color: #0000FF;
      }
      .action_active_character {
        color: #FFFF00;
      }*/
      .overlay_window {
        background-color: rgba(0, 100%, 0, 0.5);
      }
    states:
      - STATE_SHOWING
      - STATE_VISIBLE
      - STATE_ENABLED
      - STATE_SENSITIVE
    roles:
      ROLE_PUSH_BUTTON: actuate
      ROLE_TOGGLE_BUTTON: actuate
      ROLE_COMBO_BOX: actuate
      ROLE_MENU: actuate
      ROLE_MENU_ITEM: actuate
      ROLE_PAGE_TAB: actuate_non_selected
      ROLE_RADIO_BUTTON: actuate
      ROLE_SPIN_BUTTON: actuate
      ROLE_CHECK_BOX: actuate
      ROLE_CHECK_MENU_ITEM: actuate
      ROLE_LINK: actuate
      ROLE_TEXT: focus
      ROLE_ENTRY: focus
      ROLE_PASSWORD_TEXT: focus
      ROLE_SLIDER: focus
      ROLE_DIAL: actuate
      ROLE_DATE_EDITOR: focus
functions:
  actuate:
    match:
      - action: '.*'
    return: native
    else:
      match:
        - states:
          - STATE_FOCUSABLE
      return: press
      else:
        return: click
  actuate_non_selected:
    match:
      - states:
          - STATE_SELECTED
        invert: true
    call: actuate
  focus:
    match:
      - states:
          - STATE_FOCUSABLE
      - states:
          - STATE_FOCUSED
        invert: true
    return: focus