anchors:
  -
  -
lockfile: "/tmp/goodnight_mouse.pid"
rules:
  - &default_rule
    condition:
      - application: ".*"
    characters:
      [
        q,
        w,
        j,
        r,
        t,
        y,
        u,
        i,
        o,
        p,
        a,
        s,
        d,
        f,
        g,
        h,
        n,
        e,
        l,
        z,
        x,
        c,
        v,
        b,
        k,
        m,
      ]
    triggers:
      - modifiers: { super }
        key: g
        press: true
        flags: {}
      - modifiers: { super, shift }
        key: G
        press: true
        flags: { alternative }
    css: |
      .overlay_window {
        background-color: rgba(100%, 0%, 0%, 0.05);
        font-family: 'IBM Plex Mono', monospace;
        font-weight: bold;
        font-size: 14px;
      }
    states: { showing, visible, enabled, sensitive }
    roles: &default_roles
      # normal things that would be clicked with the mouse
      # avoiding native actions those that cause popup windows are bad
      push_button: &actuate
        condition:
          - flags: { alternative }
            invert: true
        then:
          condition:
            - states: { focusable }
          return:
            - &default_action
              type: action
              css: |
                .action_box {
                  background-color: #000;
                  border: 1px solid #FFF;
                  padding: 1px 3px;
                  border-radius: 3px;
                }
                .action_character {
                  color: #0F0;
                }
                .action_character_active {
                  color: #00F;
                }
              x: $x
              y: $y + $widget_height / 2 - $popup_height / 2
              execute:
                - type: focus
                - type: key
                  key: Return
                  action: click
          else:
            return:
              - <<: *default_action
                execute:
                  - type: mouse
                    button: 1
                    action: click
        else:
          return:
            - <<: *default_action
              execute:
                - type: mouse
                  button: 1
                  action: click
                  modifiers: { control, shift }
      toggle_button: *actuate
      combo_box: *actuate
      radio_button: *actuate
      spin_button: *actuate
      check_box: *actuate
      check_menu_item: *actuate
      link: *actuate
      # TODO: make explicit clicks
      menu: *actuate
      menu_item: *actuate

      # tabs of a page have a unique flow
      # generally the 'x' isn't available
      page_tab: &page_tab_action
        condition:
          - states: { selected }
        then:
          return:
            - type: rule
              check_children: false
            - &close_page_tab
              <<: *default_action
              x: $x + $widget_width - $popup_width
              css: |
                .action_box {
                  background-color: #000;
                  border: 1px solid #FFF;
                  padding: 1px 3px;
                  border-radius: 3px;
                }
                .action_character {
                  color: #F00;
                }
                .action_character_active {
                  color: #00F;
                }
              execute:
                - type: mouse
                  button: 2
                  action: click
        else:
          return:
            - type: rule
              check_children: false
            - <<: *default_action
              execute:
                - type: mouse
                  button: 1
                  action: click
            - *close_page_tab

      # things that want focus
      text: &focus
        condition:
          - states: { focusable }
          - states: { focused }
            invert: true
        return:
          - <<: *default_action
            execute:
              - type: focus
      entry: *focus
      password_text: *focus
      slider: *focus
      dial: *actuate
      date_editor: *focus

      # list items are often click able but also sometimes not
      # so only do so if it has an action on it
      list_item: &only_native
        condition:
          - action: ".*"
        return:
          - <<: *default_action
            #execute:
            #- type: action
            #match: '.*'
      tree_item: *only_native
