anchors:
  - &default_action
    css: |
      .action_box {
        background-color: #000;
        border: 3px solid #FFF;
        padding: 1px 3px;
        border-radius: 3px;
      }
      .action_character {
        color: #0F0;
      }
      .action_character_active {
        color: #00F;
      }
    x: $x + $widget_width - $popup_width
    y: $y + $widget_height - $popup_height
  - &actuate
    # condition:
    #   - action: '.*'
    # return:
    #   - <<: *default_action
    #     execute:
    #       - type: action
    #         match: '.*'
    # else:
    condition:
      - states: { focusable }
    return:
      - <<: *default_action
        execute:
          - type: focus
          - type: key
            key: Return
            action: click
    else:
      return:
        - <<: *default_action
          execute:
            - type: mouse
              button: 1
              action: click
  - &actuate_non_selected
    condition:
      - states: { selected }
        invert: true
    then: *actuate
  - &focus
    condition:
      - states: { focusable }
      - states: { focused }
        invert: true
    return:
      - <<: *default_action
        execute:
          - type: focus
  - &only_native
    condition:
      - action: 'select'
    return:
      - <<: *default_action
        execute:
          - type: action
            match: '.*'
lockfile: "/tmp/goodnight_mouse.pid"
rules:
  - &default_rule
    condition:
      - application: '.*'
    characters: [ f, j, d, k, g, h, s, l, a ]
    # characters: [a, b, c]
    triggers:
      - modifiers: { super }
        key: d
        press: true
        flags: { default }
    css: |
      .overlay_window {
        background-color: rgba(100%, 0%, 0%, 0.05);
      }
    states: { showing, visible, enabled, sensitive }
    roles: &default_roles
      push_button: *actuate
      toggle_button: *actuate
      combo_box: *actuate
      menu: *actuate
      menu_item: *actuate
      page_tab: *actuate_non_selected
      radio_button: *actuate
      spin_button: *actuate
      check_box: *actuate
      check_menu_item: *actuate
      link: *actuate
      text: *focus
      entry: *focus
      password_text: *focus
      slider: *focus
      dial: *actuate
      date_editor: *focus
      list_item: *only_native